# Generated by Django 6.1 on 2026-08-10 07:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OEM", "Original Equipment Manufacturer"),
                            ("VENDOR", "Vendor / Manufacturer"),
                            ("ENGINEER", "Primexa Staff Engineer"),
                        ],
                        default="OEM",
                        max_length=20,
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="System-wide unique enterprise ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("accepted_terms_date", models.DateTimeField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EngineerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engineer_id_code",
                    models.CharField(
                        blank=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        default="Staff Manufacturing Engineer",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="e.g., CNC Tooling, Quality Assurance, FAI Inspection",
                        max_length=100,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "assigned_zone",
                    models.CharField(
                        blank=True, default="Pune / Maharashtra Hub", max_length=100
                    ),
                ),
                ("is_active_reviewer", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OEMProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oem_id_code",
                    models.CharField(
                        blank=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary procurement or engineering lead",
                        max_length=150,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Head of Supply Chain, Senior Engineer",
                        max_length=100,
                    ),
                ),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, help_text="Official registered office address"
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=255)),
                (
                    "industry_sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTOMOTIVE", "Automotive & EV"),
                            ("AEROSPACE", "Aerospace & Defense"),
                            ("MEDICAL", "Medical Devices & Healthcare"),
                            ("INDUSTRIAL", "Industrial Heavy Machinery"),
                            ("CONSUMER", "Consumer Electronics & Appliances"),
                            ("OTHER", "Other Engineering Sector"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "typical_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Briefly describe what parts you regularly outsource",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oem_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_id_code",
                    models.CharField(
                        blank=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=150)),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        help_text="Manager or Production In-charge",
                        max_length=150,
                    ),
                ),
                ("quality_incharge_name", models.CharField(blank=True, max_length=150)),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                (
                    "cin_number",
                    models.CharField(
                        blank=True,
                        help_text="Only for Pvt Ltd",
                        max_length=21,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.TextField(blank=True, help_text="Full shop address"),
                ),
                (
                    "turnover_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LESS_50L", "Less than 50 Lakhs"),
                            ("50L_1CR", "50 Lakhs to 1 Crore"),
                            ("1CR_5CR", "1 Crore to 5 Crores"),
                            ("5CR_10CR", "5 Crores to 10 Crores"),
                            ("10CR_50CR", "10 Crores to 50 Crores"),
                            ("50CR_100CR", "50 Crores to 100 Crores"),
                            ("ABOVE_100CR", "Above 100 Crores"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "past_customers",
                    models.TextField(blank=True, help_text="Key companies served"),
                ),
                (
                    "certificates",
                    models.TextField(blank=True, help_text="e.g., ISO 9001, AS9100"),
                ),
                (
                    "machinery_list",
                    models.TextField(
                        blank=True, help_text="List of CNCs, VMCs, Lathes, etc."
                    ),
                ),
                ("production_capacity", models.CharField(blank=True, max_length=255)),
                ("min_part_size", models.CharField(blank=True, max_length=100)),
                ("max_part_size", models.CharField(blank=True, max_length=100)),
                (
                    "quality_instruments",
                    models.TextField(
                        blank=True,
                        help_text="e.g., CMM, Vernier, Micrometers, Height Gauge",
                    ),
                ),
                ("machine_capacity", models.CharField(blank=True, max_length=255)),
                ("current_workload_percentage", models.IntegerField(default=0)),
                ("is_open_to_subcontract", models.BooleanField(default=True)),
                (
                    "operating_hours",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("8", "8 Hours"),
                            ("12", "12 Hours"),
                            ("24", "24 Hours"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "has_inhouse_programmer",
                    models.BooleanField(
                        default=False,
                        help_text="Check if in-house programmer is available",
                    ),
                ),
                (
                    "interested_in_low_cost_inserts",
                    models.BooleanField(
                        default=False, help_text="Interested in low-cost insert supply?"
                    ),
                ),
                (
                    "current_inserts_used",
                    models.TextField(
                        blank=True, help_text="Brands, Types, and Present Prices paid"
                    ),
                ),
                (
                    "other_services_needed",
                    models.TextField(
                        blank=True, help_text="Any other service needed from our side"
                    ),
                ),
                (
                    "shop_photo",
                    models.ImageField(blank=True, null=True, upload_to="shop_photos/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
