# Generated by Django 6.1 on 2026-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="current_workload_percentage",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="is_open_to_subcontract",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="machine_capacity",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="certificates",
            field=models.TextField(blank=True, help_text="e.g., ISO 9001, AS9100"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="cin_number",
            field=models.CharField(
                blank=True, help_text="Only for Pvt Ltd", max_length=21, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="current_inserts_used",
            field=models.TextField(
                blank=True, help_text="Brands, Types, and Present Prices paid"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="has_inhouse_programmer",
            field=models.BooleanField(
                default=False, help_text="Check if in-house programmer is available"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="interested_in_low_cost_inserts",
            field=models.BooleanField(
                default=False, help_text="Interested in low-cost insert supply?"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="location",
            field=models.TextField(blank=True, help_text="Full shop address"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="machinery_list",
            field=models.TextField(
                blank=True, help_text="List of CNCs, VMCs, Lathes, etc."
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="manager_name",
            field=models.CharField(
                blank=True, help_text="Manager or Production In-charge", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="max_part_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="min_part_size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="operating_hours",
            field=models.CharField(
                blank=True,
                choices=[("8", "8 Hours"), ("12", "12 Hours"), ("24", "24 Hours")],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="other_services_needed",
            field=models.TextField(
                blank=True, help_text="Any other service needed from our side"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="past_customers",
            field=models.TextField(blank=True, help_text="Key companies served"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="production_capacity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="quality_incharge_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="quality_instruments",
            field=models.TextField(
                blank=True, help_text="e.g., CMM, Vernier, Micrometers, Height Gauge"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="shop_photo",
            field=models.ImageField(blank=True, null=True, upload_to="shop_photos/"),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="turnover_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LESS_50L", "Less than 50 Lakhs"),
                    ("50L_1CR", "50 Lakhs to 1 Crore"),
                    ("1CR_5CR", "1 Crore to 5 Crores"),
                    ("5CR_10CR", "5 Crores to 10 Crores"),
                    ("10CR_50CR", "10 Crores to 50 Crores"),
                    ("50CR_100CR", "50 Crores to 100 Crores"),
                    ("ABOVE_100CR", "Above 100 Crores"),
                ],
                max_length=20,
            ),
        ),
    ]
