# Generated by Django 6.1 on 2026-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_loginactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="industrial_area",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="is_public_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="is_public_profile_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="pin_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="public_description",
            field=models.TextField(
                blank=True,
                help_text="Public company description for the vendor profile.",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="public_enquiry_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="public_enquiry_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="public_slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL slug for the public vendor profile.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
