# Generated by Django 6.1 on 2026-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_vendorprofile_current_workload_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oemprofile",
            name="industry",
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="billing_address",
            field=models.TextField(
                blank=True, help_text="Official registered office address"
            ),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="contact_person_name",
            field=models.CharField(
                blank=True,
                help_text="Primary procurement or engineering lead",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="e.g., Head of Supply Chain, Senior Engineer",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="industry_sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTOMOTIVE", "Automotive & EV"),
                    ("AEROSPACE", "Aerospace & Defense"),
                    ("MEDICAL", "Medical Devices & Healthcare"),
                    ("INDUSTRIAL", "Industrial Heavy Machinery"),
                    ("CONSUMER", "Consumer Electronics & Appliances"),
                    ("OTHER", "Other Engineering Sector"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="typical_requirements",
            field=models.TextField(
                blank=True,
                help_text="Briefly describe what parts you regularly outsource (e.g., CNC milling, injection molds, sheet metal)",
            ),
        ),
    ]
