# Generated by Django 6.1 on 2026-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_oemprofile_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oemprofile",
            name="industry",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="current_workload_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="is_open_to_subcontract",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="machine_capacity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="oemprofile",
            name="typical_requirements",
            field=models.TextField(
                blank=True,
                help_text="Briefly describe what parts you regularly outsource",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OEM", "Original Equipment Manufacturer"),
                    ("VENDOR", "Vendor / Manufacturer"),
                    ("ENGINEER", "Primexa Staff Engineer"),
                ],
                default="OEM",
                max_length=20,
            ),
        ),
    ]
