# Generated by Django 6.1 on 2026-08-07 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_oemprofile_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oemprofile",
            name="oem_id_code",
            field=models.CharField(
                blank=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-wide unique enterprise ID",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="vendor_id_code",
            field=models.CharField(
                blank=True, editable=False, max_length=50, unique=True
            ),
        ),
        migrations.CreateModel(
            name="EngineerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engineer_id_code",
                    models.CharField(
                        blank=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        default="Staff Manufacturing Engineer",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="e.g., CNC Tooling, Quality Assurance, FAI Inspection",
                        max_length=100,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "assigned_zone",
                    models.CharField(
                        blank=True, default="Pune / Maharashtra Hub", max_length=100
                    ),
                ),
                ("is_active_reviewer", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
