# Generated by Django 6.0.3 on 2026-09-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0004_vendorprofile_max_batch_quantity_and_more")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OEM", "Original Equipment Manufacturer"),
                    ("VENDOR", "Vendor / Manufacturer"),
                    ("ENGINEER", "Primexa Staff Engineer"),
                    ("EXPERT", "Independent Manufacturing Expert"),
                ],
                default="OEM",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expert_id_code", models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("expertise", models.TextField(help_text="Processes, domains, and technical skills.")),
                ("industries", models.TextField(blank=True)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("about", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_public_profile", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="expert_profile", to="users.user")),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_type", models.CharField(choices=[("FIND_VENDOR", "Find a vendor for a task"), ("FIND_EXPERT", "Find an expert for a project"), ("END_TO_END", "Prototype to delivery / complete assembly")], max_length=20)),
                ("project_title", models.CharField(max_length=255)),
                ("task_description", models.TextField()),
                ("required_processes", models.TextField(blank=True)),
                ("quantity_or_scope", models.CharField(blank=True, max_length=150)),
                ("budget_range", models.CharField(blank=True, max_length=100)),
                ("target_timeline", models.CharField(blank=True, max_length=150)),
                ("contact_name", models.CharField(max_length=150)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("NEW", "New"), ("CONTACTED", "Contacted"), ("QUALIFIED", "Qualified"), ("CLOSED", "Closed")], default="NEW", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_requests", to="users.user")),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
