# Generated by Django 6.0.3 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0005_alter_user_role_expertprofile_servicerequest")]

    operations = [
        migrations.AddField(model_name="expertprofile", name="availability_note", field=models.CharField(blank=True, help_text="For example: Available weekdays 10:00–16:00 IST.", max_length=200)),
        migrations.AddField(model_name="expertprofile", name="certifications", field=models.TextField(blank=True, help_text="Professional certifications and qualifications.")),
        migrations.AddField(model_name="expertprofile", name="projects", field=models.TextField(blank=True, help_text="Completed projects and case studies suitable for public display.")),
    ]
