# Generated by Django 6.1 on 2026-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_expertprofile_availability_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oemprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oemprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL slug for the OEM business profile.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
