# Generated by Django 6.1 on 2026-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_oemprofile_is_approved_oemprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL slug for the public expert profile.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
