# Generated by Django 6.1 on 2026-08-10 07:29

import django.db.models.deletion
import exchange.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CADModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        default=exchange.models.generate_tracking_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="New Requirement", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="secure_cad_models/"
                    ),
                ),
                (
                    "job_category",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Component Job"),
                            ("ASSEMBLY", "Assembly (Multiple Drawings / ZIP Package)"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                (
                    "work_nature",
                    models.CharField(
                        choices=[
                            ("NEW", "New Development (Prototype & FAI)"),
                            ("PRODUCTION", "Regular Production / Batch Run"),
                        ],
                        default="PRODUCTION",
                        max_length=20,
                    ),
                ),
                ("batch_quantity", models.PositiveIntegerField(default=1)),
                (
                    "target_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "vendor_qualifications_required",
                    models.TextField(blank=True, null=True),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("fai_remarks", models.TextField(blank=True, null=True)),
                (
                    "accepted_vendor_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "platform_margin_percentage",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "final_primexa_quote",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("oem_approval_at", models.DateTimeField(blank=True, null=True)),
                ("oem_approval_remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Primexa Review"),
                            ("PUBLISHED", "Published to Vendors"),
                            ("BID_PLACED", "Bids Placed by Vendors"),
                            (
                                "REVIEWED_SHORTLISTED",
                                "Primexa Engineer Reviewed & Shortlisted",
                            ),
                            (
                                "FAI_PENDING",
                                "First Article Inspection (FAI) Pending Approval",
                            ),
                            ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                            (
                                "OEM_APPROVAL_PENDING",
                                "Commercial Quote Sent to OEM - Approval Pending",
                            ),
                            ("OEM_APPROVED", "OEM Approved - Ready for Final Award"),
                            ("OEM_REJECTED", "OEM Rejected Commercial Quote"),
                            ("REJECTED", "Requirement Rejected"),
                            ("VENDOR_AWARDED", "Vendor Awarded & Subcontracted"),
                            (
                                "FINAL_VENDOR_ONBOARDED",
                                "Final Vendor Onboarded & Order Placed",
                            ),
                            ("COMPLETED", "Order Completed"),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "oem_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_oem_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcontracted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_cad_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("delivery_days", models.PositiveIntegerField()),
                ("proposal_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="exchange.cadmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REQUIREMENT_SUBMITTED", "Requirement Submitted"),
                            ("REQUIREMENT_PUBLISHED", "Requirement Published"),
                            ("NDA_SIGNED", "NDA Signed"),
                            ("BID_SUBMITTED", "Bid Submitted"),
                            ("BID_SHORTLISTED", "Bid Shortlisted"),
                            ("COMMERCIAL_PREPARED", "Commercial Proposal Prepared"),
                            (
                                "COMMERCIAL_PROPOSAL_SENT",
                                "Commercial Proposal Sent to OEM",
                            ),
                            ("OEM_APPROVAL_PENDING", "OEM Approval Required"),
                            ("OEM_REVISION_REQUESTED", "OEM Revision Requested"),
                            ("OEM_APPROVED", "OEM Approved"),
                            (
                                "OEM_COMMERCIAL_APPROVED",
                                "OEM Commercial Proposal Approved",
                            ),
                            ("OEM_REJECTED", "OEM Rejected"),
                            (
                                "OEM_COMMERCIAL_REJECTED",
                                "OEM Commercial Proposal Rejected",
                            ),
                            ("FINAL_VENDOR_AWARD", "Final Vendor Award"),
                            ("FINAL_AWARD_CONFIRMATION", "Final Award Confirmation"),
                            ("VENDOR_ACCEPTED", "Vendor Accepted Award"),
                            ("FAI_REQUIRED", "FAI Required"),
                            ("FAI_SUBMITTED", "FAI Submitted"),
                            ("FAI_APPROVED", "FAI Approved"),
                            ("PRODUCTION_STARTED", "Production Started"),
                            ("PRODUCTION_COMPLETED", "Production Completed"),
                            ("DISPATCHED", "Order Dispatched"),
                            ("DELIVERED", "Order Delivered"),
                            ("ORDER_COMPLETED", "Order Completed"),
                            ("REMINDER", "Reminder"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkloadTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nda_signed_by_sub", models.BooleanField(default=False)),
                ("agreed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "signature_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_transfers",
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "sub_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_work",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
