# Generated by Django 6.1 on 2026-08-07 02:37

import django.db.models.deletion
import exchange.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CADModel",
            fields=[
                (
                    "tracking_number",
                    models.CharField(
                        default=exchange.models.generate_tracking_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Requirement", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describe the specific requirements here.",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="secure_cad_models/"
                    ),
                ),
                (
                    "job_category",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Component Job"),
                            ("ASSEMBLY", "Assembly (Multiple Drawings / ZIP Package)"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                (
                    "work_nature",
                    models.CharField(
                        choices=[
                            ("NEW", "New Development (Prototype & FAI)"),
                            ("PRODUCTION", "Regular Production / Batch Run"),
                        ],
                        default="PRODUCTION",
                        max_length=20,
                    ),
                ),
                ("batch_quantity", models.PositiveIntegerField(default=1)),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Target price per piece in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "vendor_qualifications_required",
                    models.TextField(
                        blank=True,
                        help_text="e.g., ISO 9001 mandatory, CMM inspection required",
                        null=True,
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Target delivery date agreed with the vendor",
                        null=True,
                    ),
                ),
                (
                    "fai_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Engineer or OEM feedback during First Article Inspection",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Primexa Review"),
                            ("BID_PLACED", "Bids Placed by Vendors"),
                            (
                                "REVIEWED_SHORTLISTED",
                                "Primexa Engineer Reviewed & Shortlisted",
                            ),
                            (
                                "FAI_PENDING",
                                "First Article Inspection (FAI) Pending Approval",
                            ),
                            ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                            ("REJECTED", "Requirement Rejected"),
                            (
                                "FINAL_VENDOR_ONBOARDED",
                                "Final Vendor Onboarded & Order Placed",
                            ),
                            ("COMPLETED", "Order Completed"),
                            ("PUBLISHED", "Published to Vendors"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkloadTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nda_signed_by_sub", models.BooleanField(default=False)),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "sub_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_work",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
