# Generated by Django 6.1 on 2026-08-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "FAI Pending"),
                            ("SUBMITTED", "FAI Submitted"),
                            ("APPROVED", "FAI Approved"),
                            ("REJECTED", "FAI Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inspection_report",
                    models.FileField(
                        blank=True, null=True, upload_to="fai/inspection_reports/"
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True, null=True)),
                (
                    "dimensional_report",
                    models.FileField(
                        blank=True, null=True, upload_to="fai/dimensional_reports/"
                    ),
                ),
                (
                    "material_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="fai/material_certificates/"
                    ),
                ),
                (
                    "other_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="fai/other_documents/"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("engineer_remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cad_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fai_record",
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fai_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fai_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
