# Generated by Django 6.1 on 2026-08-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total or per-piece quoted price in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        help_text="Estimated delivery time in days"
                    ),
                ),
                (
                    "proposal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes, machine capacity, or terms",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
