# Generated by Django 6.0.3 on 2026-08-14 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_fairecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadmodel",
            name="vendor_awarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when Primexa issued the final vendor award.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="vendor_committed_delivery_date",
            field=models.DateField(
                blank=True,
                help_text="Delivery date committed by the awarded vendor.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUIREMENT_SUBMITTED", "Requirement Submitted"),
                    ("REQUIREMENT_PUBLISHED", "Requirement Published"),
                    ("NDA_SIGNED", "NDA Signed"),
                    ("BID_SUBMITTED", "Bid Submitted"),
                    ("BID_SHORTLISTED", "Bid Shortlisted"),
                    ("COMMERCIAL_PREPARED", "Commercial Proposal Prepared"),
                    ("COMMERCIAL_PROPOSAL_SENT", "Commercial Proposal Sent to OEM"),
                    ("OEM_APPROVAL_PENDING", "OEM Approval Required"),
                    ("OEM_REVISION_REQUESTED", "OEM Revision Requested"),
                    ("OEM_APPROVED", "OEM Approved"),
                    ("OEM_COMMERCIAL_APPROVED", "OEM Commercial Proposal Approved"),
                    ("OEM_REJECTED", "OEM Rejected"),
                    ("OEM_COMMERCIAL_REJECTED", "OEM Commercial Proposal Rejected"),
                    ("FINAL_VENDOR_AWARD", "Final Vendor Award"),
                    ("FINAL_AWARD_CONFIRMATION", "Final Award Confirmation"),
                    ("VENDOR_ACCEPTED", "Vendor Accepted Award"),
                    ("FAI_REQUIRED", "FAI Required"),
                    ("FAI_SUBMITTED", "FAI Submitted"),
                    ("FAI_APPROVED", "FAI Approved"),
                    ("PRODUCTION_STARTED", "Production Started"),
                    ("PRODUCTION_COMPLETED", "Production Completed"),
                    ("DISPATCHED", "Order Dispatched"),
                    ("DELIVERED", "Order Delivered"),
                    ("ORDER_COMPLETED", "Order Completed"),
                    ("REMINDER", "Reminder"),
                    ("DELIVERY_RISK", "Delivery Risk Alert"),
                    ("SYSTEM_ALERT", "System Alert"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryRiskAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_delivery_date", models.DateField()),
                ("revised_delivery_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("MACHINE_BREAKDOWN", "Machine Breakdown"),
                            ("RAW_MATERIAL_DELAY", "Raw Material Delay"),
                            ("POWER_UTILITY", "Power / Utility Issue"),
                            ("MANPOWER", "Manpower Issue"),
                            ("QUALITY_REWORK", "Quality / Rework Issue"),
                            ("CAPACITY", "Capacity Issue"),
                            ("TRANSPORT", "Transport Issue"),
                            ("EXTERNAL_DEPENDENCY", "Customer / External Dependency"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PRODUCTION", "In Production"),
                            ("PARTIALLY_COMPLETED", "Partially Completed"),
                            (
                                "COMPLETED_AWAITING_DISPATCH",
                                "Completed - Awaiting Dispatch",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity_completed", models.PositiveIntegerField(default=0)),
                ("quantity_remaining", models.PositiveIntegerField(default=0)),
                ("issue_description", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(blank=True, null=True, upload_to="delivery_risk/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Engineer Review"),
                            ("RECOVERY_REQUESTED", "Recovery Plan Requested"),
                            ("ACCEPTED", "Revised Delivery Accepted"),
                            ("RESOLVED", "Resolved"),
                            ("REALLOCATED", "Work Reallocated"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("engineer_remarks", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_risk_alerts",
                        to="exchange.cadmodel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_delivery_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_risk_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
