# Generated by Django 6.1 on 2026-08-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_bid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadmodel",
            name="accepted_vendor_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost quoted by the selected subcontractor vendor",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="final_primexa_quote",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final price quoted to the OEM by Primexa",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="platform_margin_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Primexa's markup percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="selected_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Subcontracted vendor handling production behind the scenes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcontracted_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workloadtransfer",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workloadtransfer",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 cryptographic proof of agreement",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Primexa Review"),
                    ("BID_PLACED", "Bids Placed by Vendors"),
                    ("REVIEWED_SHORTLISTED", "Primexa Engineer Reviewed & Shortlisted"),
                    ("FAI_PENDING", "First Article Inspection (FAI) Pending Approval"),
                    ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                    ("REJECTED", "Requirement Rejected"),
                    (
                        "VENDOR_AWARDED",
                        "Vendor Awarded & Subcontracted (Managed by Primexa)",
                    ),
                    ("FINAL_VENDOR_ONBOARDED", "Final Vendor Onboarded & Order Placed"),
                    ("COMPLETED", "Order Completed"),
                    ("PUBLISHED", "Published to Vendors"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workloadtransfer",
            name="agreed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
