# Generated by Django 6.0.3 on 2026-08-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_cadmodel_vendor_awarded_at_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Primexa Review"),
                    ("PUBLISHED", "Published to Vendors"),
                    ("BID_PLACED", "Bids Placed by Vendors"),
                    ("REVIEWED_SHORTLISTED", "Primexa Engineer Reviewed & Shortlisted"),
                    ("FAI_PENDING", "First Article Inspection (FAI) Pending Approval"),
                    ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                    ("FAI_REJECTED", "FAI Rejected"),
                    (
                        "OEM_APPROVAL_PENDING",
                        "Commercial Quote Sent to OEM - Approval Pending",
                    ),
                    ("OEM_APPROVED", "OEM Approved - Ready for Final Award"),
                    ("OEM_REJECTED", "OEM Rejected Commercial Quote"),
                    ("REJECTED", "Requirement Rejected"),
                    ("VENDOR_AWARDED", "Vendor Awarded & Subcontracted"),
                    ("FINAL_VENDOR_ONBOARDED", "Final Vendor Onboarded & Order Placed"),
                    ("COMPLETED", "Order Completed"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ManufacturingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("TURNING", "Turning"),
                            ("MILLING", "Milling"),
                            ("VMC", "VMC"),
                            ("HMC", "HMC"),
                            ("CNC", "CNC"),
                            ("GRINDING", "Grinding"),
                            ("EDM", "EDM"),
                            ("WIRE_CUT", "Wire Cut"),
                            ("FABRICATION", "Fabrication"),
                            ("WELDING", "Welding"),
                            ("HEAT_TREATMENT", "Heat Treatment"),
                            ("HARDENING", "Hardening"),
                            ("ANNEALING", "Annealing"),
                            ("COATING", "Coating"),
                            ("ANODIZING", "Anodizing"),
                            ("PLATING", "Plating"),
                            ("PAINTING", "Painting"),
                            ("SHOT_BLASTING", "Shot Blasting"),
                            ("LASER_CUTTING", "Laser Cutting"),
                            ("INSPECTION", "Inspection"),
                            ("ASSEMBLY", "Assembly"),
                            ("PACKAGING", "Packaging"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("required_machine", models.CharField(blank=True, max_length=150)),
                ("tolerance_requirement", models.CharField(blank=True, max_length=150)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_processes",
                        to="exchange.cadmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="VendorMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=255)),
                ("machine_type", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("model_number", models.CharField(blank=True, max_length=150)),
                ("controller", models.CharField(blank=True, max_length=150)),
                ("work_envelope", models.CharField(blank=True, max_length=255)),
                ("accuracy", models.CharField(blank=True, max_length=150)),
                ("maximum_load", models.CharField(blank=True, max_length=150)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="users.vendorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorMachineAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_from", models.DateTimeField()),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="exchange.vendormachine",
                    ),
                ),
            ],
            options={
                "ordering": ["available_from"],
            },
        ),
        migrations.CreateModel(
            name="VendorMachineProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("TURNING", "Turning"),
                            ("MILLING", "Milling"),
                            ("VMC", "VMC"),
                            ("HMC", "HMC"),
                            ("CNC", "CNC"),
                            ("GRINDING", "Grinding"),
                            ("EDM", "EDM"),
                            ("WIRE_CUT", "Wire Cut"),
                            ("FABRICATION", "Fabrication"),
                            ("WELDING", "Welding"),
                            ("LASER_CUTTING", "Laser Cutting"),
                            ("HEAT_TREATMENT", "Heat Treatment"),
                            ("HARDENING", "Hardening"),
                            ("ANNEALING", "Annealing"),
                            ("COATING", "Coating"),
                            ("ANODIZING", "Anodizing"),
                            ("PLATING", "Plating"),
                            ("PAINTING", "Painting"),
                            ("SHOT_BLASTING", "Shot Blasting"),
                            ("INSPECTION", "Inspection"),
                            ("ASSEMBLY", "Assembly"),
                            ("PACKAGING", "Packaging"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="exchange.vendormachine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorProcessCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("TURNING", "Turning"),
                            ("MILLING", "Milling"),
                            ("VMC", "VMC"),
                            ("HMC", "HMC"),
                            ("CNC", "CNC"),
                            ("GRINDING", "Grinding"),
                            ("EDM", "EDM"),
                            ("WIRE_CUT", "Wire Cut"),
                            ("FABRICATION", "Fabrication"),
                            ("WELDING", "Welding"),
                            ("LASER_CUTTING", "Laser Cutting"),
                            ("HEAT_TREATMENT", "Heat Treatment"),
                            ("HARDENING", "Hardening"),
                            ("ANNEALING", "Annealing"),
                            ("COATING", "Coating"),
                            ("ANODIZING", "Anodizing"),
                            ("PLATING", "Plating"),
                            ("PAINTING", "Painting"),
                            ("SHOT_BLASTING", "Shot Blasting"),
                            ("INSPECTION", "Inspection"),
                            ("ASSEMBLY", "Assembly"),
                            ("PACKAGING", "Packaging"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capability_description", models.TextField(blank=True)),
                ("tolerance_capability", models.CharField(blank=True, max_length=150)),
                ("material_experience", models.CharField(blank=True, max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_capabilities",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "process_type"),
                        name="unique_vendor_process_capability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material Supplier"),
                            ("MANUFACTURING", "Manufacturing / Machining"),
                            ("FABRICATION", "Fabrication"),
                            ("SURFACE_TREATMENT", "Surface Treatment"),
                            ("HEAT_TREATMENT", "Heat Treatment"),
                            ("INSPECTION", "Inspection / Testing"),
                            ("PACKAGING", "Packaging"),
                            ("TRANSPORTATION", "Transportation / Logistics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "category"),
                        name="unique_vendor_service_category",
                    )
                ],
            },
        ),
    ]
