# Generated by Django 6.1 on 2026-08-07 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_cadmodel_accepted_vendor_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("cad_model", "vendor"), name="unique_vendor_bid_per_requirement"
            ),
        ),
    ]
