# Generated by Django 6.1 on 2026-08-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_bid_unique_vendor_bid_per_requirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bid",
            name="unique_vendor_bid_per_requirement",
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Primexa Review"),
                    ("PUBLISHED", "Published to Vendors"),
                    ("BID_PLACED", "Bids Placed by Vendors"),
                    ("REVIEWED_SHORTLISTED", "Primexa Engineer Reviewed & Shortlisted"),
                    ("FAI_PENDING", "First Article Inspection (FAI) Pending Approval"),
                    ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                    ("REJECTED", "Requirement Rejected"),
                    ("VENDOR_AWARDED", "Vendor Awarded & Subcontracted"),
                    ("FINAL_VENDOR_ONBOARDED", "Final Vendor Onboarded & Order Placed"),
                    ("COMPLETED", "Order Completed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_cad_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workloadtransfer",
            name="cad_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workload_transfers",
                to="exchange.cadmodel",
            ),
        ),
    ]
