# Generated by Django 6.0.3 on 2026-08-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_alter_cadmodel_status_manufacturingprocess_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("TURNING", "Turning"),
                            ("MILLING", "Milling"),
                            ("VMC", "VMC"),
                            ("HMC", "HMC"),
                            ("CNC", "CNC"),
                            ("GRINDING", "Grinding"),
                            ("EDM", "EDM"),
                            ("WIRE_CUT", "Wire Cut"),
                            ("FABRICATION", "Fabrication"),
                            ("WELDING", "Welding"),
                            ("LASER_CUTTING", "Laser Cutting"),
                            ("HEAT_TREATMENT", "Heat Treatment"),
                            ("HARDENING", "Hardening"),
                            ("ANNEALING", "Annealing"),
                            ("COATING", "Coating"),
                            ("ANODIZING", "Anodizing"),
                            ("PLATING", "Plating"),
                            ("PAINTING", "Painting"),
                            ("SHOT_BLASTING", "Shot Blasting"),
                            ("INSPECTION", "Inspection"),
                            ("ASSEMBLY", "Assembly"),
                            ("PACKAGING", "Packaging"),
                            ("TRANSPORTATION", "Transportation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("process_name", models.CharField(blank=True, max_length=150)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("material_required", models.BooleanField(default=False)),
                ("material_description", models.TextField(blank=True)),
                ("drawing_reference", models.CharField(blank=True, max_length=255)),
                ("technical_specification", models.TextField(blank=True)),
                ("tolerance_requirement", models.CharField(blank=True, max_length=255)),
                (
                    "surface_finish_requirement",
                    models.CharField(blank=True, max_length=255),
                ),
                ("machine_requirement", models.CharField(blank=True, max_length=255)),
                (
                    "estimated_process_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("is_outsourcable", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cad_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_processes",
                        to="exchange.cadmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ProcessBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("delivery_days", models.PositiveIntegerField()),
                ("machine_available_from", models.DateTimeField(blank=True, null=True)),
                ("material_included", models.BooleanField(default=False)),
                (
                    "material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tooling_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "inspection_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("proposal_notes", models.TextField(blank=True)),
                ("is_lumpsum_offer", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_bids",
                        to="exchange.vendorprocesscapability",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_bids",
                        to="exchange.vendormachine",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_bids",
                        to="exchange.requirementprocess",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="requirementprocess",
            constraint=models.UniqueConstraint(
                fields=("cad_model", "sequence"),
                name="unique_requirement_process_sequence",
            ),
        ),
    ]
