# Generated by Django 6.1 on 2026-08-08 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0005_remove_bid_unique_vendor_bid_per_requirement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="delivery_days",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bid",
            name="offered_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="bid",
            name="proposal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="accepted_vendor_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="fai_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="final_primexa_quote",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="platform_margin_percentage",
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="selected_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcontracted_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Primexa Review"),
                    ("PUBLISHED", "Published to Vendors"),
                    ("BID_PLACED", "Bids Placed by Vendors"),
                    ("REVIEWED_SHORTLISTED", "Primexa Engineer Reviewed & Shortlisted"),
                    ("FAI_PENDING", "First Article Inspection (FAI) Pending Approval"),
                    ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                    ("REJECTED", "Requirement Rejected"),
                    ("VENDOR_AWARDED", "Vendor Awarded & Subcontracted"),
                    ("FINAL_VENDOR_ONBOARDED", "Final Vendor Onboarded & Order Placed"),
                    ("COMPLETED", "Order Completed"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="target_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="vendor_qualifications_required",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workloadtransfer",
            name="signature_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
