# Generated by Django 6.1 on 2026-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0005_requirementprocess_processbid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprocesscapability",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vendormachineprocess",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("TURNING", "Turning"),
                    ("MILLING", "Milling"),
                    ("VMC", "VMC"),
                    ("HMC", "HMC"),
                    ("CNC", "CNC"),
                    ("GRINDING", "Grinding"),
                    ("EDM", "EDM"),
                    ("WIRE_CUT", "Wire Cut"),
                    ("FABRICATION", "Fabrication"),
                    ("WELDING", "Welding"),
                    ("LASER_CUTTING", "Laser Cutting"),
                    ("HEAT_TREATMENT", "Heat Treatment"),
                    ("HARDENING", "Hardening"),
                    ("ANNEALING", "AnneALING"),
                    ("COATING", "Coating"),
                    ("ANODIZING", "Anodizing"),
                    ("PLATING", "Plating"),
                    ("PAINTING", "Painting"),
                    ("SHOT_BLASTING", "Shot Blasting"),
                    ("INSPECTION", "Inspection"),
                    ("ASSEMBLY", "Assembly"),
                    ("PACKAGING", "Packaging"),
                    ("TRANSPORTATION", "Transportation"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vendorprocesscapability",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("TURNING", "Turning"),
                    ("MILLING", "Milling"),
                    ("VMC", "VMC"),
                    ("HMC", "HMC"),
                    ("CNC", "CNC"),
                    ("GRINDING", "Grinding"),
                    ("EDM", "EDM"),
                    ("WIRE_CUT", "Wire Cut"),
                    ("FABRICATION", "Fabrication"),
                    ("WELDING", "Welding"),
                    ("LASER_CUTTING", "Laser Cutting"),
                    ("HEAT_TREATMENT", "Heat Treatment"),
                    ("HARDENING", "Hardening"),
                    ("ANNEALING", "AnneALING"),
                    ("COATING", "Coating"),
                    ("ANODIZING", "Anodizing"),
                    ("PLATING", "Plating"),
                    ("PAINTING", "Painting"),
                    ("SHOT_BLASTING", "Shot Blasting"),
                    ("INSPECTION", "Inspection"),
                    ("ASSEMBLY", "Assembly"),
                    ("PACKAGING", "Packaging"),
                    ("TRANSPORTATION", "Transportation"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
