# Generated by Django 6.0.3 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0006_vendorprocesscapability_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="bid", name="development_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="labour_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="machine_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="material_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="other_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="other_cost_description", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="bid", name="overhead_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="packaging_and_transport_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="production_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="prototype_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="quality_assurance_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name="bid", name="tooling_cost", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
    ]
