# Generated by Django 6.1 on 2026-08-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0006_alter_bid_delivery_days_alter_bid_offered_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadmodel",
            name="oem_approval_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="oem_approval_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cadmodel",
            name="oem_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_oem_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Primexa Review"),
                    ("PUBLISHED", "Published to Vendors"),
                    ("BID_PLACED", "Bids Placed by Vendors"),
                    ("REVIEWED_SHORTLISTED", "Primexa Engineer Reviewed & Shortlisted"),
                    ("FAI_PENDING", "First Article Inspection (FAI) Pending Approval"),
                    ("FAI_APPROVED", "FAI Approved - Ready for Production"),
                    (
                        "OEM_APPROVAL_PENDING",
                        "Commercial Quote Sent to OEM - Approval Pending",
                    ),
                    ("OEM_APPROVED", "OEM Approved - Ready for Final Award"),
                    ("OEM_REJECTED", "OEM Rejected Commercial Quote"),
                    ("REJECTED", "Requirement Rejected"),
                    ("VENDOR_AWARDED", "Vendor Awarded & Subcontracted"),
                    ("FINAL_VENDOR_ONBOARDED", "Final Vendor Onboarded & Order Placed"),
                    ("COMPLETED", "Order Completed"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
    ]
