# Generated by Django 6.1 on 2026-09-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0007_bid_cost_breakdown"),
        ("users", "0003_vendorprofile_city_vendorprofile_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorShopPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vendor_shop_photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_photos",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_type",
                    models.CharField(
                        choices=[
                            ("ISO_9001", "ISO 9001"),
                            ("IATF_16949", "IATF 16949"),
                            ("AS9100", "AS9100"),
                            ("ISO_13485", "ISO 13485"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("certificate_number", models.CharField(blank=True, max_length=150)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_records",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "certification_type"),
                        name="unique_vendor_certification",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("AUTOMOTIVE", "Automotive"),
                            ("EV", "EV"),
                            ("AEROSPACE", "Aerospace"),
                            ("DEFENCE", "Defence"),
                            ("MEDICAL_DEVICES", "Medical Devices"),
                            ("INDUSTRIAL", "Industrial"),
                            ("ELECTRONICS", "Electronics"),
                            ("CONSUMER", "Consumer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industries_served",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "industry"), name="unique_vendor_industry"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("ALUMINIUM", "Aluminium"),
                            ("MILD_STEEL", "Mild Steel"),
                            ("STAINLESS_STEEL", "Stainless Steel"),
                            ("TOOL_STEEL", "Tool Steel"),
                            ("TITANIUM", "Titanium"),
                            ("INCONEL", "Inconel"),
                            ("BRASS", "Brass"),
                            ("COPPER", "Copper"),
                            ("ENGINEERING_PLASTICS", "Engineering Plastics"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("specification_notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "material_type"),
                        name="unique_vendor_material",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorQualityInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("CMM", "CMM"),
                            ("VERNIER", "Vernier Caliper"),
                            ("MICROMETER", "Micrometer"),
                            ("HEIGHT_GAUGE", "Height Gauge"),
                            ("SURFACE_ROUGHNESS_TESTER", "Surface Roughness Tester"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_instrument_records",
                        to="users.vendorprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "instrument_type"),
                        name="unique_vendor_quality_instrument",
                    )
                ],
            },
        ),
    ]
