# Generated by Django 6.1 on 2026-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange",
            "0008_vendorshopphoto_vendorcertification_vendorindustry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vendormachine",
            name="accuracy_microns",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="axis_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="bar_capacity_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="between_centers_distance_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="chuck_size_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="machine_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="maximum_turning_diameter_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="maximum_turning_length_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="maximum_workpiece_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="spindle_power_kw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="spindle_speed_rpm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="x_travel_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="y_travel_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendormachine",
            name="z_travel_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
