# Generated by Django 6.1 on 2026-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0009_vendormachine_accuracy_microns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadmodel",
            name="sourcing_flow",
            field=models.CharField(
                choices=[
                    (
                        "PRIMEXA_MANAGED",
                        "Primexa Managed Sourcing (Full Quality & Supplier Management)",
                    ),
                    (
                        "DIRECT_RFQ",
                        "Direct Network RFQ (Direct Bids & Quotations from Vendor Network)",
                    ),
                ],
                default="PRIMEXA_MANAGED",
                help_text="Choose whether Primexa manages quality & sourcing or if vendors submit direct quotations.",
                max_length=30,
            ),
        ),
    ]
