# Generated by Django 6.1 on 2026-09-21 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0010_cadmodel_sourcing_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadmodel",
            name="targeted_vendors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Targeted vendors for Direct RFQ (OEM: 1 to 5, Engineer: all or selected).",
                related_name="targeted_cad_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
